name: Demonstrate GitHub Actions Features

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          node fruits.js
      - name: Check if basket.json exists
        run: |
          if [ -f basket.json ]; then
            echo "basket.json generated successfully."
          else
            echo "basket.json not found. Something went wrong!"
            exit 1
          fi

  test-job:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Fruit Test
        run: |
          node test-fruits.js
          if [ $? -eq 0 ]; then
            echo "Test passed."
          else
            echo "Test failed."
            exit 1
          fia

  independent-job:
    runs-on: ubuntu-latest
    steps:
      - name: Independent Step
        run: |
          echo "This job is independent of others."

